sudo: true

language: bash

services:
  - docker

env:
  global:
    - DOCKERHUB="user/endpoint"

jobs:
  include:
    - stage: BuildImage
      if: (NOT (type IN (pull_request)))
      script:
        # Determine tag
        - export CALIBRE_VERSION=$(curl -sX GET "https://api.github.com/repos/kovidgoyal/calibre/releases/latest" | awk '/tag_name/{print $4;exit}' FS='[""]')
        # Build image
        - docker build --no-cache -t ${DOCKERHUB}:${TRAVIS_COMMIT} .
        - docker tag ${DOCKERHUB}:${TRAVIS_COMMIT} ${DOCKERHUB}:latest
        - docker tag ${DOCKERHUB}:${TRAVIS_COMMIT} ${DOCKERHUB}:${CALIBRE_VERSION}
        # Login to DockerHub
        - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
        # Push all of the tags
        - docker push ${DOCKERHUB}:${TRAVIS_COMMIT}
        - docker push ${DOCKERHUB}:latest
        - docker push ${DOCKERHUB}:${CALIBRE_VERSION}
